service: expressInAWSDemo #Name of your App
provider:
 name: aws
 runtime: nodejs20.x
 memorySize: 512
 timeout: 15
 stage: production
 region: eu-central-1
functions:
 api:
  handler: lambda.universal
  events:
    - http: ANY {proxy+}
    - http: ANY /